#!/bin/bash
apt-get install procps -yapt-get install sysstat -y
check_cpu() {     #CPU利用率与负载     UTIL=`vmstat |awk '{if(NR==3)print 100-$15"%"}'`     USER=`vmstat |awk '{if(NR==3)print $13"%"}'`     SYS=`vmstat |awk '{if(NR==3)print $14"%"}'`     IOWAIT=`vmstat |awk '{if(NR==3)print $16"%"}'`     echo "-------------CPU利用率与负载---------------"     echo "Util: $UTIL"     echo "User use: $USER"     echo "System use: $SYS"     echo "I/O wait: $IOWAIT"}
check_disk_load() {    #硬盘I/O负载    UTIL=`iostat -x -k |awk '/^[v|s]/{OFS=": ";print $1,$NF"%"}'`    READ=`iostat -x -k |awk '/^[v|s]/{OFS=": ";print $1,$6"KB"}'`    WRITE=`iostat -x -k |awk '/^[v|s]/{OFS=": ";print $1,$7"KB"}'`    IOWAIT=`vmstat |awk '{if(NR==3)print $16"%"}'`    echo "-------------硬盘I/O负载---------------"    echo -e "Util:"    echo -e "${UTIL}"    echo -e "I/O Wait: $IOWAIT"    echo -e "Read/s:\n$READ"    echo -e "Write/s:\n$WRITE"}
check_disk_use() {    #硬盘利用率    part=$(df -h |awk 'BEGIN{OFS="="}/^\/dev/{print $6,$2,$3,$4,int($5)}')    for p in $part;do        mount=$(echo $p |cut -d"=" -f1)        total=$(echo $p |cut -d"=" -f2)        used=$(echo $p |cut -d"=" -f3)        free=$(echo $p |cut -d"=" -f4)        used_parent=$(echo $p |cut -d"=" -f5)        if [ $used_parent -ge 13 ];then           echo "-------------硬盘利用率---------------"           echo "挂载点: $mount"           echo "总大小: $total"           echo "使用: $used"           echo "剩余：$free"        fi     done}
check_disk_inode() {    #硬盘inode利用率    INODE_USE=$(df -i | awk 'NR>1 {printf "%-20s %-10s %-10s %-10s %-10s %-s\n", $1,$2, $3,$4, $5,$6}')    echo "-------------硬盘inode利用率---------------"    echo $INODE_USE}
check_mem_use() {    #内存利用率    MEM_TOTAL=`free -m |awk '{if(NR==2)printf "%.1f",$2/1024}END{print "G"}'`    USE=`free -m |awk '{if(NR==3) printf "%.1f",$3/1024}END{print "G"}'`    FREE=`free -m |awk '{if(NR==3) printf "%.1f",$4/1024}END{print "G"}'`    CACHE=`free -m |awk '{if(NR==2) printf "%.1f",($6+$7)/1024}END{print "G"}'`    echo "-------------内存利用率---------------"    echo -e "Total: $MEM_TOTAL"    echo -e "Use: $USE"    echo -e "Free: $FREE"    echo -e "Cache: $CACHE"}
check_tcp_status() {    #网络连接状态    COUNT=`netstat -antp |awk '{status[$6]++}END{for(i in status) print i,status[i]}'`    echo -e "网络连接状态:\n$COUNT"}
check_cpu_top10() {    #占用CPU高的前10个进程    CPU_TOP=`ps -eo pid,user,%cpu,%mem,command --sort=-%cpu | head -n 11`    echo -e "占用CPU高的前10个进程:\n$CPU_TOP"}
check_mem_top10() {    #占用内存高的前10个进程    MEM_TOP=`ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -n 11`    echo -e "占用内存高的前10个进程:\n$MEM_TOP"}
check_traffic() {    #检查进入与进出流量    eth=`ip link show | awk -F': ' '/^[0-9]+: / {print $2}' |grep -Ev 'lo'`    OLD_IN=`ifconfig $eth |awk -F'[: ]+' '/bytes/{if(NR==8)print $4;else if(NR==5)print $6}'`    OLD_OUT=`ifconfig $eth |awk -F'[: ]+' '/bytes/{if(NR==8)print $9;else if(NR==7)print $6}'`    sleep 1    NEW_IN=`ifconfig $eth |awk -F'[: ]+' '/bytes/{if(NR==8)print $4;else if(NR==5)print $6}'`    NEW_OUT=`ifconfig $eth |awk -F'[: ]+' '/bytes/{if(NR==8)print $9;else if(NR==7)print $6}'`    IN=`awk 'BEGIN{printf "%.1f\n",'$((${NEW_IN}-${OLD_IN}))'/1024/128}'`    OUT=`awk 'BEGIN{printf "%.1f\n",'$((${NEW_OUT}-${OLD_OUT}))'/1024/128}'`    echo "进入流量${IN}MB/s 进出流量${OUT}MB/s"}
check_cpucheck_disk_loadcheck_disk_usecheck_disk_inodecheck_mem_usecheck_tcp_statuscheck_cpu_top10check_mem_top10check_traffic